import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/Navbar";
//import styles from "../styles/modules/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Encontre sua vaga Python no Pyjobs</title>
        <meta name="PyJobs" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <section className="container">
        <div className="infoBlock">
          <h2 className="section__title">
            Encontre aqui as melhores vagas e profissionais Python{" "}
          </h2>
          <p className="section__text">
            PyJobs é o maior site de profissionais Python do Brasil. Nossos
            anúncios alcançam uma rede de mais de 15 mil profissionais Python, e
            temos mais de 2 anos de experiência com recrutamento.{" "}
          </p>
          <button className="section__button">Quero cadastrar uma vaga</button>
          <p className="section__text">
            ou veja as <a href="#">vagas listadas abaixo</a>
          </p>
        </div>
        <div className="section__img">
          <Image
            width={833}
            height={814}
            src={"/assets/images/cadastroVaga.png"}
            alt="Foto de desenvolvedor de costas programando"
          />
        </div>
      </section>
    </>
  );
}
